spring:
  profiles:
    active: mysql

---
spring:
  profiles: h2
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver

#logging
logging:
  file: logs/h2-logging-file.log
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
  pattern:
    # console에 찍히는 로그 형식 정의
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    # console에서 로그는 위에 형식으로 찍히지만 파일로 씌여질 때 해당 패턴으로 찍는다. 
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

---
spring:
  profiles: mysql
  datasource:
    #hikari:
    basquiat:
      jdbc-url: jdbc:mysql://localhost:3306/basquiat?autoReconnect=true
      username: basquiat
      password: basquiat
      driver-class-name: com.mysql.cj.jdbc.Driver

#logging
logging:
  file: logs/mysql-logging-file.log
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
  pattern:
    # console에 찍히는 로그 형식 정의
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    # console에서 로그는 위에 형식으로 찍히지만 파일로 씌여질 때 해당 패턴으로 찍는다. 
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"